In [62]:
import gym
import numpy as np
import time
import random
from IPython.display import clear_output
env = gym.make('FrozenLake-v1')


In [63]:
colunas_acoes = env.action_space.n
linhas_estados = env.observation_space.n

#tabela_q = np.random.rand(linhas_estados, colunas_acoes)
tabela_q = np.zeros((linhas_estados, colunas_acoes))
#tabela_q = np.ones((linhas_estados, colunas_acoes))
print(tabela_q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
#algoritimo que esta dando certo

todas_recompensas = []

num_episodios = 10000
num_passos_por_episodio = 100

taxa_de_aprendizado = 0.1
taxa_de_desconto = 0.99

taxa_exploration = 0.1  # ou qualquer valor no intervalo [0, 1]
max_taxa_exploration = 1
min_taxa_exploration = 0.01
taxa_de_decaimento_da_exploração = 0.001

# Q-learning algoritmo
for episodio in range(num_episodios):
    estado = env.reset()
    done = False
    recompensas_episodio_atual = 0

    for passo in range(num_passos_por_episodio):
        limite_taxa_exploration = random.uniform(0, 1)

        if limite_taxa_exploration > max_taxa_exploration:  # Comparar com max_taxa_exploration
            action = np.argmax(tabela_q[estado, :])
        else:
            action = env.action_space.sample()

        novo_estado, recompensa, done, info = env.step(action)

        # Atualizar tabela Q
        tabela_q[estado, action] = tabela_q[estado, action] * (1 - taxa_de_aprendizado) + \
                                    taxa_de_aprendizado * (recompensa + taxa_de_desconto * np.max(tabela_q[novo_estado, :]))

        estado = novo_estado
        recompensas_episodio_atual += recompensa

        if done == True:
            break

        # Atualizar taxa de exploração
        taxa_exploration = min_taxa_exploration + \
                           (max_taxa_exploration - min_taxa_exploration) * np.exp(-taxa_de_decaimento_da_exploração * episodio)

    todas_recompensas.append(recompensas_episodio_atual)

# Calcular a recompensa média de um total de 1000 episódios
media_total_recompensas = np.array_split(np.array(todas_recompensas), num_episodios / 1000)
count = 1000


In [65]:
print("RECOMPENSA MEDIA DE TODOS OS EPISODIOS:")
for r in media_total_recompensas:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

#print atualização da tabela Q
print("\n\n********TABELA_Q********\n")
print(tabela_q)

RECOMPENSA MEDIA DE TODOS OS EPISODIOS:
1000 :  0.014000000000000005
2000 :  0.016000000000000007
3000 :  0.012000000000000004
4000 :  0.01900000000000001
5000 :  0.022000000000000013
6000 :  0.012000000000000004
7000 :  0.015000000000000006
8000 :  0.013000000000000005
9000 :  0.012000000000000004
10000 :  0.013000000000000005


********TABELA_Q********

[[0.46449805 0.45893462 0.46189622 0.45059824]
 [0.33167514 0.31635897 0.18020581 0.4449936 ]
 [0.43459588 0.42800669 0.42727653 0.42454966]
 [0.32941302 0.28782056 0.33114385 0.41653914]
 [0.47545505 0.30351853 0.27213404 0.22779415]
 [0.         0.         0.         0.        ]
 [0.46918248 0.27698777 0.26281341 0.09519044]
 [0.         0.         0.         0.        ]
 [0.28603817 0.3348572  0.34783939 0.498748  ]
 [0.31480063 0.60006007 0.41044777 0.48397244]
 [0.64810911 0.57840012 0.43728679 0.31414195]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3402221  0.48657311 0.69061

In [66]:
for episodio in range(5):
  estado = env.reset()
  done = False
  print("*******episodio ", episodio+1, "*****\n\n\n\n")
  time.sleep(1)
  for passo in range(num_passos_por_episodio):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)

    action =  np.argmax(tabela_q[estado,:])
    novo_estado,recompensa,done,info = env.step(action)

    if done:
      clear_output(wait=True)
      env.render()
      if recompensa == 1:
        print("*****PARABENS!!! Você venceu*****")
        time.sleep(3)
      else:
        print("*****GAME OVER*****")
        time.sleep(3)
      clear_output(wait=True)
      break

    estado = novo_estado

env.close()

*****PARABENS!!! Você venceu*****
